"""
Django settings for ywm_qs project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Dict


# Build paths inside the project like this: BASE_DIR / 'subdir'.


BASE_DIR = Path(__file__).resolve().parent.parent
WEB_DIR = BASE_DIR.parent
LOG_DIR = os.path.join(WEB_DIR,"logs")




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-re9#=br+((2(gi39y!c20odhoq4tnk-)ph58l(sdu0ep1qa@!7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG_MODE"))

ALLOWED_HOSTS = [os.getenv("APP_DOMAIN"),"localhost","127.0.0.1"] 

CORS_ALLOWED_ORIGINS = [
    f"https://{os.getenv("APP_DOMAIN")}",
    f"https://{os.environ.get('SHOPIFY_DOMAIN')}",
    "http://127.0.0.1"
]
CORS_ALLOW_HEADERS = [
    "X-Shopify-Site",
    "Content-Type"
]

def filtered_additions(key):
    return [x for x in filter(lambda x:x is not None and len(x)>0,os.environ.get(key,"").split(','))]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_redis',
    'root.apps.RootConfig',
    'shopify_sites.apps.ShopifySitesConfig',
    "shopify_proxy.apps.ShopifyProxyConfig",
    'webhooks.apps.WebhooksConfig',
    "django_tasks",
]+filtered_additions("APPS")



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shopify_sites.middleware.LoginProtection',
    'shopify_sites.middleware.ShopifyEmbed',
    'xyz.middleware.CorsHeaders',
]+filtered_additions("MIDDLEWARE")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",  # Replace with your Redis URL
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            #"COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor", # Optional compression
        },
        "TIMEOUT":None
    }
}

ROOT_URLCONF = 'xyz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                "root.context_procesors.sidebarNav",
                "root.context_procesors.env",
                "root.context_procesors.proxyDetails",
                "root.context_procesors.shopifyNav"
            ]+filtered_additions("CONTEXT_PROCESSORS")
        },
    },
]

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

WSGI_APPLICATION = 'xyz.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST":os.getenv("DB_HOST","localhost"),
        "NAME":os.getenv("DB_NAME"),
        "USER":os.getenv("DB_USER","crapp"),
        "PASSWORD":os.getenv("DB_PASSWORD"),
        "OPTIONS": {
            "read_default_file": "/path/to/my.cnf",
            'charset': 'utf8mb4',
            'collation': 'utf8mb4_unicode_ci',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'  # Example: Eastern Time

USE_I18N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_ROOT = os.path.join(WEB_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = []

FILES_ROOT = os.path.join(BASE_DIR,"files")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = False


EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND","django.core.mail.backends.smtp.EmailBackend")

EMAIL_USE_TLS = bool(os.environ.get("EMAIL_USE_TLS"))
EMAIL_PORT = int(os.environ.get("EMAIL_PORT"))
EMAIL_HOST_USER = os.environ.get("DEFAULT_EMAIL")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',  # Or 'DEBUG', 'WARNING', 'ERROR', 'CRITICAL'
            'class': 'logging.FileHandler',
            'filename': os.path.join(WEB_DIR, 'logs','django.log'), # Path to your log file
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'xyz': { # Replace 'your_app_name' with your actual app name
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False, # Set to False to prevent messages from propagating to parent loggers
        },
         'xyz': { # Replace 'your_app_name' with your actual app name
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False, # Set to False to prevent messages from propagating to parent loggers
        },
        '': { # Root logger - captures logs from any Python application without a specific logger
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_EMAIL")
USE_DJANGO_Q_FOR_EMAILS = False  # 🆕 Use Django Q for sending ALL emails.
DJANGO_Q_AVAILABLE = False

Q_CLUSTER = {
    'name': 'DJRedis',
    'workers': 4,
    'timeout': 60,
    'retry':90,
    'django_redis': 'default',
    'catchup':True,
}

#wat
